[package]
name = "soroflare-vm"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
soroban-env-host = {version = "0.0.15", features = ["vm", "serde", "hostfn_log_fmt_values"] }
soroban-spec = "0.7.0"
soroban-ledger-snapshot = "0.7.0"
stellar-strkey = "0.0.7"
ed25519-dalek = "1.0.1"
hex = "0.4.3"
sha2 = "0.10.6"
thiserror = "1.0.31"
itertools = "0.10.5"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
ethnum = "1.3.2"